#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+	Listens on port 80.
#+	Returns a page containing "Hello World!" when queried at the root with 
#+	a curl GET request.
#+	Configures /redirect_me as a "301 Move Permanently".
#+	Includes a custom 404 page containing "Ceci n'est pas une page".
#+	Contains a custom HTTP header named X-Served-By.
#+	The value of the HTTP header is the hostname of the running server.

apt-get update
apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root   /var/www/html;
	index  index.html index.htm;

	location /redirect_me {
		return 301 https://github.com/AdebowaleGideon/;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" | sudo tee /etc/nginx/sites-available/default > /dev/null
