#!/usr/bin/env bash
# configures a new Ubuntu server with a HAProxy load-balancer

sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy=2.4.\*
sudo sed -i '/errorfile 504/a listen gideonavenue' /etc/haproxy/haproxy.cfg
sudo sed -i '/listen gideonavenue/a		bind :80' /etc/haproxy/haproxy.cfg
sudo sed -i '/bind :80/a		mode http' /etc/haproxy/haproxy.cfg
sudo sed -i '/mode http/a		server 34581-web-01 3.235.79.149:80 check' /etc/haproxy/haproxy.cfg
sudo sed -i '/server 34581-web-01 3.235.79.149:80 check/a		server 34581-web-02 54.209.196.196:80 check'
sudo sed -i '/#EXTRAOPTS="-de -m 16'/a ENABLED=1' /etc/default/haproxy
sudo service haproxy start
