#!/usr/bin/env bash
#  displays a list of currently running proceses for all users, including those
#+ which might not have a TTY (teletype i.e refers to the controlling terminal
#+ for the process.

ps -faux
