#!/usr/bin/env bash
# creates file '/var/run/myscript.pid' containing its PID
# displays 'To infinity and beyond' indefinitely
# displays 'I hate the kill command' when it receives a SIGTERM signal
# displays 'Y U no love me?!' when it receives a SIGINT signal
#  deletes the file '/var/run/myscript.pid' and terminates itself when it receives a SIGQUIT or SIGTERM

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
while true;
do
	echo "To infinity and beyond"
	trap 'echo "I hate kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
done
