#!/usr/bin/env bash
#  a Bash script that displays the content of the file /etc/passwd
#+ displaying only the username, user id, Home directory path for the user.

input="/etc/passwd"
while read -r line;
do
	echo "$line" | cut -d':' --fields=1,3,6
done < "$input"
